#!/usr/bin/env rake

require File.expand_path('../app/site', __FILE__)
require 'sprockets'
require 'yui/compressor'

task :default => :compile
task :compile => [:html, :assets]

task :html do
  site = Site.new(ENV['SITE_HOST'])
  site.view_path = File.expand_path('../views', __FILE__)
  [
    'index',
    'install'
  ].each {|f|
    site.write_html f, File.expand_path("../#{f}.html")
  }
end

task :assets do
  env = Sprockets::Environment.new
  env.append_path 'assets'
  jar = File.expand_path('../lib/yuicompressor-2.4.7.jar', __FILE__)
  env.css_compressor = YUI::CssCompressor.new(:jar_file => jar)
  env.js_compressor  = YUI::JavaScriptCompressor.new(:jar_file => jar, :munge => true)
  [
    'application.js',
    'application.scss',
    'b.js',
    'bookmarklet.js',
  ].each {|f|
    env[f].write_to(File.expand_path("../../assets/#{ f.sub(/\.scss$/, '.css') }", __FILE__))
  }
  bookmarklet = File.expand_path('../../assets/bookmarklet', __FILE__)
  File.unlink("#{bookmarklet}.txt") if File.exists?("#{bookmarklet}.txt")
  File.rename("#{bookmarklet}.js", "#{bookmarklet}.txt")
  File.open "#{bookmarklet}.txt", 'rb+' do |file|
    js = file.read
    file.pos = 0
    file.write("javascript:#{js}/*         INSTALLED */")
  end
end
