#!/usr/bin/env rake

require File.expand_path('../app/site', __FILE__)
@site = Site.new(ENV['SITE_HOST'])
@site.view_path = File.expand_path('../views', __FILE__)

task :default => :compile

task :compile do |t|
  ['index', 'install'].each {|f|
    write("#{f}.html", @site.render(f))
  }
  ['js', 'css'].each{|f|
    write("assets/application.#{f}", @site.send(f))
  }
end

def write filename, content
  path = File.expand_path('../../'+ filename, __FILE__)
  File.open path, 'w' do |file|
    file.write(content)
  end
end
